#!/usr/bin/env bash
# This script configures UFW on web-01 to block all incoming traffic except 22, 80, and 443
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw --force enable

