#!/usr/bin/env bash

# Check arguments...
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# These lines capture the values you type in the terminal
FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# This line uses those captured values to perform the transfer
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME"@"$IP":~/
